default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: lfpadmin
  password:

development:
  <<: *default
  database: connect4_development

test:
  <<: *default
  database: connect4_test

production:
  <<: *default
  database: connect4_production
  username: lfpadmin
  password: root
